name: multi_module_flutter
packages:
  - core/**
  - features/**


command:
  bootstrap:
    environment:
      sdk: ">=3.7.2 <4.0.0"
      flutter: ">=1.17.0"

    dependencies:
      dio: ^5.8.0+1

    dev_dependencies:
      flutter_lints: ^5.0.0

scripts:
  clean : melos clean
  cleanAndBootstrap : melos clean && melos bootstrap
  test :
    run: melos exec --concurrency=1 -- flutter test
  update : flutter pub outdated
  upgrade : flutter pub upgrade --major-versions

